Moved jvm_options before -jar
As of Jenkins 1.4+, it validates command line arguments.  Putting JVM
options after the -jar results in the error "Caused by:
java.lang.IllegalArgumentException: Multiple command line argument
specified" as Jenkins believes you are passing it the argument.  
Moving the jvm_options before the -jar solves this.